apiVersion: kleveross.io/v1alpha1
kind: ModelJob
metadata:
  name: modeljob-mxnet-convert
  namespace: default
spec:
  # Add fields here
  model: "harbor-harbor-core.kleveross-system/release/mxnet:v1"
  desiredTag: "harbor-harbor-core.kleveross-system/release/onnx_convert:v2"
  conversion:
    mmdnn:
      from: "MXNetParams"
      to: "ONNX"
