apiVersion: kleveross.io/v1alpha1
kind: ModelJob
metadata:
  name: modeljob-pmml-extract
  namespace: default
spec:
  # Add fields here
  model: "harbor-harbor-core.kleveross-system/release/pmml:v1"
  extraction:
    format: "PMML"