apiVersion: kleveross.io/v1alpha1
kind: ModelJob
metadata:
  name: modeljob-h5-convert
  namespace: default
spec:
  # Add fields here
  model: "harbor-harbor-core.kleveross-system/release/h5:v1"
  desiredTag: "harbor-harbor-core.kleveross-system/release/savemodel_convert:v2"
  conversion:
    mmdnn:
      from: "H5"
      to: "SavedModel"

