apiVersion: v1
kind: Secret
metadata:
  name: ormb
type: Opaque
data:
  # base64 formatted username `admin`
  ORMB_USERNAME: YWRtaW4=
  # base64 formatted password `ORMBtest12345`
  ORMB_PASSWORD: T1JNQnRlc3QxMjM0NQ==