apiVersion: v1
kind: Service
metadata:
  name: {{ include "klever-model-registry.fullname" . }}
  labels:
    {{- include "klever-model-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "klever-model-registry.selectorLabels" . | nindent 4 }}
